[package]
name = "udp_socket"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
msg_proto_lib = { path = "../msg_proto_lib"}
ctrlc-async = "3.2.2"
tokio = "1.35.1"
rand = "0.8.5"
