[package]
name = "hw11"
version = "0.1.0"
edition = "2021"

[[example]]
name = "example1"
path = "examples/example1.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
thiserror = "1.0.56"
